export const SET_SEARCHED_WEATHER = 'SET_SEARCHED_WEATHER';
export const FETCH_SEARCHED_WEATHER_FAILED = 'FETCH_SEARCHED_WEATHER_FAILED';

export const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER';
export const FETCH_CURRENT_WEATHER_FAILED = 'FETCH_CURRENT_WEATHER_FAILED';

export const ON_FETCH_WEATHER = 'ON_FETCH_WEATHER';

export const SET_CURRENT_SMOG = 'SET_CURRENT_SMOG';
export const FETCH_CURRENT_SMOG_FAILED = 'FETCH_CURRENT_SMOG_FAILED';

export const SET_LONGTERM_WEATHER = 'SET_LONGTERM_WEATHER';
export const FETCH_LONGTERM_WEATHER_FAILED = 'FETCH_LONGTERM_WEATHER_FAILED';